export const BUILT_IN = [
  "findRESubmatch",
  "partialCached",
  "safeHTMLAttr",
  "htmlUnescape",
  "base64Encode",
  "base64Decode",
  "singularize",
  "markdownify",
  "fingerprint",
  "relLangURL",
  "newScratch",
  "htmlEscape",
  "fileExists",
  "dateFormat",
  "countwords",
  "countrunes",
  "complement",
  "absLangURL",
  "unmarshal",
  "safeJSStr",
  "replaceRE",
  "pluralize",
  "intersect",
  "highlight",
  "hasSuffix",
  "hasPrefix",
  "anchorize",
  "urlquery",
  "truncate",
  "slicestr",
  "safeHTML",
  "readFile",
  "plainify",
  "humanize",
  "erroridf",
  "duration",
  "warnidf",
  "symdiff",
  "shuffle",
  "safeURL",
  "safeCSS",
  "replace",
  "readDir",
  "querify",
  "println",
  "postCSS",
  "partial",
  "modBool",
  "keyVals",
  "jsonify",
  "getJSON",
  "emojify",
  "delimit",
  "default",
  "xxhash",
  "urlize",
  "substr",
  "string",
  "sha256",
  "safeJS",
  "relURL",
  "relref",
  "printf",
  "minify",
  "getenv",
  "getCSV",
  "findRE",
  "errorf",
  "append",
  "absURL",
  "where",
  "warnf",
  "upper",
  "union",
  "toCSS",
  "title",
  "split",
  "slice",
  "print",
  "merge",
  "lower",
  "isset",
  "index",
  "group",
  "float",
  "first",
  "chomp",
  "babel",
  "apply",
  "after",
  "uniq",
  "trim",
  "time",
  "sort",
  "site",
  "sha1",
  "page",
  "last",
  "i18n",
  "hmac",
  "dict",
  "cond",
  "sub",
  "seq",
  "ref",
  "pow",
  "now",
  "not",
  "mul",
  "mod",
  "md5",
  "len",
  "int",
  "div",
  "and",
  "add",
  "or",
  "ne",
  "lt",
  "le",
  "in",
  "gt",
  "ge",
  "eq",
  "T"
];

export const FUNCTION = [
  "hugo.IsMultilingual|10",
  "hugo.IsDevelopment|10",
  "hugo.IsProduction|10",
  "hugo.IsMultihost|10",
  "hugo.Environment|10",
  "hugo.WorkingDir|10",
  "hugo.IsExtended|10",
  "hugo.CommitHash|10",
  "hugo.GoVersion|10",
  "hugo.Generator|10",
  "hugo.BuildDate|10",
  "hugo.IsServer|10",
  "hugo.Version|10",
  "hugo.Store|10",
  "hugo.Deps|10"
];

export const KEYWORD = [
  "template",
  "continue",
  "return",
  "define",
  "range",
  "break",
  "block",
  "with",
  "else",
  "try",
  "end",
  "if"
];

export const LITERAL = [
  "false",
  "true",
  "nil"
];


export const ACTION_KEYWORDS = {
  $pattern: /\w+/,
  'keyword': KEYWORD,
};

export const PIPELINE_KEYWORDS = {
   $pattern: /\w+/,
   'built_in': BUILT_IN,
   'literal': LITERAL,
};

export const FUNCTION_KEYWORDS = {
   $pattern: /\w+\.\w+/,
   'built_in': FUNCTION,
};
export const FUNCTION_REGEX = /\b(hugo.BuildDate|hugo.CommitHash|hugo.Deps|hugo.Environment|hugo.Generator|hugo.GoVersion|hugo.IsDevelopment|hugo.IsExtended|hugo.IsMultihost|hugo.IsMultilingual|hugo.IsProduction|hugo.IsServer|hugo.Store|hugo.Version|hugo.WorkingDir)\b/;

